{
  "samples": [
    "in_house_assembly_081020", 
    "sentieon_pe400_chr19",
    "in_house_assembly_082520",
    "in_house_assembly_090920",
    "in_house_assembly_091420",
    "in_house_assembly_091520"
  ],
  "ref_files": {
    "hs37d5": "/research/rv-02/home/qmao/DBs/hs37d5/hs37d5.fa"
  },
  "input_dir": "Assembly",
  "truth_dir": "/research/rv-02/home/eanderson/Simulated_Data_Wenlan/Simulated_Ref/Fasta/",
  "stratification_region_tsv": "/home-02/eanderson/Sentieon_Binning_and_Stratification/ga4gh_all_coordonly_2.tsv",
  "stratification_bed_dir": "/home-02/eanderson/Sentieon_Binning_and_Stratification/stratification_regions",
  "minimap2": "/home-02/eanderson/minimap2-2.16_x64-linux/minimap2",
  "bin_without_pid_script": "/home-02/eanderson/Sentieon_Binning_and_Stratification/bin_without_pid.py",
  "seqtk": "/research/rv-02/home/qmao/Scripts/seqtk-master/seqtk",
  "k8": "/home/eanderson/bin/k8",
  "sam_flt": "/home/eanderson/CHM-eval/dip-call/sam-flt.js",
  "samtools": "/opt/cgi-tools/bin/samtools",
  "htsbox": "/home/eanderson/CHM-eval.kit/htsbox",
  "sentieon": "/opt/sentieon-genomics-cgv0.3-201808.07/bin/sentieon",
  "bcftools": "/opt/cgi-tools/bin/bcftools",
  "label_calls": "/home-02/eanderson/Sentieon_Binning_and_Stratification/label_binned_calls_vcf_3.py",
  "stratification_to_table": "/home-02/eanderson/Sentieon_Binning_and_Stratification/stratification_to_table_3.py",
  "table_to_plot": "/home-02/eanderson/Sentieon_Binning_and_Stratification/plot_stratified_counts.py"
}
